version: '3'

shopt: [globstar]

tasks:
  test:
    cmds:
      - go build ./slog/...

  lint:
    cmds:
      - echo "All files look good"

  check:
    cmds:
      - task: test
      - task: lint

  update-slog:
    cmds:
      - rm -rf slog
      - git clone https://go.googlesource.com/go
      - defer: rm -rf go/
      - mkdir slog
      - cp -r go/src/log/slog/* slog
      - task: patch-slog

  patch-slog:
    cmds:
      - rm -rf slog/**/*_test.go
      - find slog/ -type f -name '*.go' -exec sed -i 's|"log/slog|"github.com/sagikazarmark/slog-experiments/slog|g' {} +
      - find slog/ -type f -name '*.go' -exec sed -i 's|"slices"|"golang.org/x/exp/slices"|g' {} +
